<Project Sdk="Microsoft.NET.Sdk">

    <!-- Global configuration from Directory.Build.props and Directory.Packages.props in root -->

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\WideEvents.Core\WideEvents.Core.csproj" />
    </ItemGroup>

</Project>
