<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <ProjectReference Include="..\..\src\WideEvents.AspNetCore\WideEvents.AspNetCore.csproj" />
  </ItemGroup>

</Project>
